const TEMPLATES = [
	null,
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs"  , name: "Machinegun Person"                                           },
	{ turrets: ["bTrikeMG"        ], body: "B4body-sml-trike01", propulsion: "BaBaProp"  , name: "Machinegun Trike"                                            },
	{ turrets: ["BuggyMG"         ], body: "B3body-sml-buggy01", propulsion: "BaBaProp"  , name: "Machinegun Buggy"                                            },
	{ turrets: ["BJeepMG"         ], body: "B2JeepBody"        , propulsion: "BaBaProp"  , name: "Machinegun Jeep"                                             },
	{ turrets: ["BabaRocket"      ], body: "B3bodyRKbuggy01"   , propulsion: "BaBaProp"  , name: "Scavenger Rocket Buggy"                                      },
	{ turrets: ["BabaRocket"      ], body: "B2RKJeepBody"      , propulsion: "BaBaProp"  , name: "Scavenger Rocket Jeep"                                       },
	{ turrets: ["BabaFlame"       ], body: "FireBody"          , propulsion: "BaBaProp"  , name: "Scavenger Flamer Firetruck"                                  },
	{ turrets: ["BabaFlame"       ], body: "BusBody"           , propulsion: "BaBaProp"  , name: "Scavenger Flamer Bus"                                        },
	{ turrets: ["BusCannon"       ], body: "FireBody"          , propulsion: "BaBaProp"  , name: "Scavenger Cannon Firetruck"                                  },
	{ turrets: ["BusCannon"       ], body: "BusBody"           , propulsion: "BaBaProp"  , name: "Scavenger Cannon Bus"                                        },
	{ turrets: ["MG1Mk1"          ], body: "Body1REC"          , propulsion: "wheeled01" , name: "Machinegun Viper Wheels"                                     },
	{ turrets: ["MG2Mk1"          ], body: "Body1REC"          , propulsion: "HalfTrack" , name: "Twin Machinegun Viper Half-tracks"                           },
	{ turrets: ["Cannon1Mk1"      ], body: "Body1REC"          , propulsion: "HalfTrack" , name: "Light Cannon Viper Half-tracks"                              },
	{ turrets: ["CyborgCannon"    ], body: "CyborgLightBody"   , propulsion: "CyborgLegs", name: "Heavy Gunner Cyborg Light Body Cyborg Propulsion"            },
	{ turrets: ["Cannon1Mk1"      ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Light Cannon Cobra Half-tracks"                              },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body5REC"          , propulsion: "wheeled01" , name: "Medium Cannon Cobra Wheels"                                  },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Medium Cannon Cobra Half-tracks"                             },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body8MBT"          , propulsion: "tracked01" , name: "Medium Cannon Scorpion Tracks"                               },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Cobra Half-tracks"                     },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body11ABT"         , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Python Half-tracks"                    },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body12SUP"         , propulsion: "tracked01" , name: "Hyper Velocity Cannon Mantis Tracks"                         },
	{ turrets: ["Rocket-BB"       ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Bunker Buster Cobra Half-tracks"                             },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body11ABT"         , propulsion: "HalfTrack" , name: "Assault Cannon Python Half-tracks"                           },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body12SUP"         , propulsion: "tracked01" , name: "Assault Cannon Mantis Tracks"                                },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body6SUPP"         , propulsion: "tracked01" , name: "Assault Cannon Panther Tracks"                               },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body11ABT"         , propulsion: "tracked01" , name: "Heavy Cannon Python Tracks"                                  },
	{ turrets: ["Bomb1-VTOL-LtHE" ], body: "Body2SUP"          , propulsion: "V-Tol"     , name: "VTOL Cluster Bomb Bay Leopard VTOL"                          },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body2SUP"          , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Leopard VTOL"                             },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body9REC"          , propulsion: "tracked01" , name: "Heavy Cannon Tiger Tracks"                                   },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"          , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks"                            },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                     },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Rail Gun Retribution Tracks"                                 },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Gauss Cannon Vengeance Tracks"                               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                  },
];
