const TEMPLATES = [
	null,
	null,
	null,
	null,
	null,
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs", name: "Machinegun Person"          },
	{ turrets: ["bTrikeMG"        ], body: "B4body-sml-trike01", propulsion: "BaBaProp", name: "Machinegun Trike"           },
	{ turrets: ["BuggyMG"         ], body: "B3body-sml-buggy01", propulsion: "BaBaProp", name: "Machinegun Buggy"           },
	{ turrets: ["BJeepMG"         ], body: "B2JeepBody"        , propulsion: "BaBaProp", name: "Machinegun Jeep"            },
	// { turrets: ["BabaRocket"      ], body: "B2RKJeepBody"      , propulsion: "BaBaProp", name: "Scavenger Rocket Jeep"      },
	// { turrets: ["BabaRocket"      ], body: "B3bodyRKbuggy01"   , propulsion: "BaBaProp", name: "Scavenger Rocket Buggy"     },
	// { turrets: ["BabaFlame"       ], body: "FireBody"          , propulsion: "BaBaProp", name: "Scavenger Flamer Firetruck" },
	// { turrets: ["BabaFlame"       ], body: "BusBody"           , propulsion: "BaBaProp", name: "Scavenger Flamer Bus"       },
	{ turrets: ["BusCannon"       ], body: "FireBody"          , propulsion: "BaBaProp", name: "Scavenger Cannon Firetruck"           },
	{ turrets: ["BusCannon"       ], body: "BusBody"           , propulsion: "BaBaProp", name: "Scavenger Cannon Bus"                 },
	{ turrets: ["Cannon1Mk1"      ], body: "Body4ABT"          , propulsion: "hover01" , name: "Light Cannon Bug Hover"               },
	{ turrets: ["Cannon1Mk1"      ], body: "Body4ABT"          , propulsion: "hover01" , name: "Light Cannon Bug Hover"               },
	{ turrets: ["Cannon1Mk1"      ], body: "Body8MBT"          , propulsion: "hover01" , name: "Light Cannon Scorpion Hover"          },
	{ turrets: ["Cannon1Mk1"      ], body: "Body8MBT"          , propulsion: "hover01" , name: "Light Cannon Scorpion Hover"          },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body8MBT"          , propulsion: "hover01" , name: "Medium Cannon Scorpion Hover"         },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body8MBT"          , propulsion: "hover01" , name: "Medium Cannon Scorpion Hover"         },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body8MBT"          , propulsion: "hover01" , name: "Hyper Velocity Cannon Scorpion Hover" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body8MBT"          , propulsion: "hover01" , name: "Hyper Velocity Cannon Scorpion Hover" },
	{ turrets: ["Rocket-BB"       ], body: "Body4ABT"          , propulsion: "hover01" , name: "Bunker Buster Bug Hover"              },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body8MBT"          , propulsion: "hover01" , name: "Assault Cannon Scorpion Hover"        },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body8MBT"          , propulsion: "hover01" , name: "Assault Cannon Scorpion Hover"        },
	{ turrets: ["Rocket-BB"       ], body: "Body8MBT"          , propulsion: "hover01" , name: "Bunker Buster Scorpion Hover"         },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body12SUP"         , propulsion: "hover01" , name: "Medium Cannon Mantis Hover"           },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body12SUP"         , propulsion: "hover01" , name: "Medium Cannon Mantis Hover"           },
	{ turrets: ["Rocket-BB"       ], body: "Body12SUP"         , propulsion: "hover01" , name: "Bunker Buster Mantis Hover"           },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body12SUP"         , propulsion: "hover01" , name: "Heavy Cannon Mantis Hover"            },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body12SUP"         , propulsion: "hover01" , name: "Heavy Cannon Mantis Hover"            },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body12SUP"         , propulsion: "hover01" , name: "Twin Assault Cannon Mantis Hover"     },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body12SUP"         , propulsion: "hover01" , name: "Twin Assault Cannon Mantis Hover"     },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body11ABT"         , propulsion: "hover01" , name: "Twin Assault Cannon Python Hover"     },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body11ABT"         , propulsion: "hover01" , name: "Twin Assault Cannon Python Hover"     },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"          , propulsion: "hover01" , name: "Twin Assault Cannon Tiger Hover"      },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"          , propulsion: "hover01" , name: "Twin Assault Cannon Tiger Hover"      },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Needle Gun Tiger Hover"               },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Needle Gun Tiger Hover"               },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Needle Gun Tiger Hover"               },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Needle Gun Tiger Hover"               },
	{ turrets: ["RailGun2Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Rail Gun Tiger Hover"                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Rail Gun Tiger Hover"                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Rail Gun Tiger Hover"                 },
	{ turrets: ["RailGun2Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Rail Gun Tiger Hover"                 },
	{ turrets: ["RailGun3Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Gauss Cannon Tiger Hover"             },
	{ turrets: ["RailGun3Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Gauss Cannon Tiger Hover"             },
	{ turrets: ["RailGun3Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Gauss Cannon Tiger Hover"             },
	{ turrets: ["RailGun3Mk1"     ], body: "Body9REC"          , propulsion: "hover01" , name: "Gauss Cannon Tiger Hover"             },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "hover01" , name: "Gauss Cannon Vengeance Hover"         },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "hover01" , name: "Gauss Cannon Vengeance Hover"         },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "hover01" , name: "Gauss Cannon Vengeance Hover"         },
	{ turrets: ["RailGun3Mk1"     ], body: "Body10MBT"         , propulsion: "hover01" , name: "Gauss Cannon Vengeance Hover"         },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "hover01" , name: "Gauss Cannon Wyvern Hover"            },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "hover01" , name: "Gauss Cannon Wyvern Hover"            },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "hover01" , name: "Gauss Cannon Wyvern Hover"            },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "hover01" , name: "Gauss Cannon Wyvern Hover"            },
];
