const TEMPLATES = [
	null,
	null,
	null,
	null,
	null,
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs", name: "Machinegun Person"          },
	{ turrets: ["bTrikeMG"        ], body: "B4body-sml-trike01", propulsion: "BaBaProp", name: "Machinegun Trike"           },
	{ turrets: ["BJeepMG"         ], body: "B2JeepBody"        , propulsion: "BaBaProp", name: "Machinegun Jeep"            },
	{ turrets: ["BuggyMG"         ], body: "B3body-sml-buggy01", propulsion: "BaBaProp", name: "Machinegun Buggy"           },
	// { turrets: ["BabaRocket"      ], body: "B2RKJeepBody"      , propulsion: "BaBaProp", name: "Scavenger Rocket Jeep"      },
	// { turrets: ["BabaRocket"      ], body: "B3bodyRKbuggy01"   , propulsion: "BaBaProp", name: "Scavenger Rocket Buggy"     },
	// { turrets: ["BabaFlame"       ], body: "FireBody"          , propulsion: "BaBaProp", name: "Scavenger Flamer Firetruck" },
	// { turrets: ["BabaFlame"       ], body: "BusBody"           , propulsion: "BaBaProp", name: "Scavenger Flamer Bus"       },
	{ turrets: ["BusCannon"       ], body: "FireBody"          , propulsion: "BaBaProp", name: "Scavenger Cannon Firetruck" },
	{ turrets: ["BusCannon"       ], body: "BusBody"           , propulsion: "BaBaProp", name: "Scavenger Cannon Bus"       },
	{ turrets: ["Cannon1Mk1"      ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Light Cannon Leopard Half-tracks" },
	{ turrets: ["Mortar1Mk1"      ], body: "Body2SUP"       , propulsion: "wheeled01" , name: "Mortar Leopard Wheels" },
	{ turrets: ["CyborgCannon"    ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "Heavy Gunner Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Rocket-MRL"      ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Mini-Rocket Array Leopard Half-tracks" },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Medium Cannon Panther Half-tracks" },
	{ turrets: ["Cyb-Wpn-Grenade" ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "*Cyborg Grenade Weapon* Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Medium Cannon Panther Tracks" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Panther Half-tracks" },
	{ turrets: ["Mortar3ROTARYMk1"], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Pepperpot Panther Tracks" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body2SUP"       , propulsion: "tracked01" , name: "Hyper Velocity Cannon Panther Tracks" },
	{ turrets: ["Rocket-BB"       ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Bunker Buster Leopard Half-tracks" },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Assault Cannon Panther Half-tracks" },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Assault Cannon Panther Tracks" },
	{ turrets: ["Cyb-Hvywpn-Mcannon"], body: "CyborgHeavyBody", propulsion: "CyborgLegs", name: "Super Heavy-Gunner Cyborg Heavy Body Cyborg Propulsion" },
	{ turrets: ["Rocket-MRL-Hvy"  ], body: "Body2SUP"       , propulsion: "tracked01" , name: "Heavy Rocket Array Leopard Tracks" },
	{ turrets: ["Rocket-MRL-Hvy"  ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Heavy Rocket Array Panther Tracks" },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Heavy Cannon Panther Half-tracks" },
	{ turrets: ["Bomb1-VTOL-LtHE" ], body: "Body2SUP"       , propulsion: "V-Tol"     , name: "VTOL Cluster Bomb Bay Leopard VTOL" },
	{ turrets: ["Rocket-BB"       ], body: "Body2SUP"       , propulsion: "V-Tol"     , name: "Bunker Buster Leopard VTOL" },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Heavy Cannon Panther Tracks" },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body9REC"       , propulsion: "tracked01" , name: "Heavy Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" }
];
